[webservers]
13.126.95.132 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/app-servers-key ansible_ssh_common_args='-o StrictHostKeyChecking=no'
13.232.68.247 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/app-servers-key ansible_ssh_common_args='-o StrictHostKeyChecking=no'
13.206.124.185 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/app-servers-key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

