[webservers]
43.205.208.57 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/app-servers-key ansible_ssh_common_args='-o StrictHostKeyChecking=no'
13.203.229.71 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/app-servers-key ansible_ssh_common_args='-o StrictHostKeyChecking=no'
13.233.107.67 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/app-servers-key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

